# Generated by Django 5.0.4 on 2024-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Mi Empleado', 'verbose_name_plural': 'Empleados de la Empresa'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='image',
        ),
        migrations.AddField(
            model_name='empleado',
            name='Habilidades',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
    ]
